### PR TITLE
Display monitored objects' graphs in their detail views

### LINKED ISSUE #27: Display Graph in Detailview
Each host and service should display the graph in its detailview. The action link "Graphite" should be removed.

### LINKED ISSUE #32: Save Graphite page as dashboard
Save graph selection in "Graphite" page as a dashboard.

### LINKED ISSUE #34: Enhance graph selection in Graphite page
Use the same filter in the Graphite page that we use in overview pages. This unifies the web interface and gives the user much more options to show a selection of graphs.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #27
fixes #32
fixes #34

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@bobapple FYI: Fortunately (NOT) I've done #27, #32 and #34 in this one branch.

**Comment by lazyfrosch** [comment]
@Al2Klimov why `milestone/v1.0.0`?

**Comment by Al2Klimov** [comment]
@lazyfrosch Y not?

**Comment by lazyfrosch** [comment]
Aren't we using GitHub flow? Development to master? https://guides.github.com/introduction/flow/

**Comment by Al2Klimov** [comment]
@lazyfrosch `milestone/v1.0.0` will be merged into `master` once complete.

**Pull request closed without merging**
