### PR TITLE
remove quotes around $service variable

### PR DESCRIPTION
**Pull request by prometheanfire**
This fixes https://dev.icinga.org/issues/11572

This still leaves $hostname being quoted, I don't know if that needs to go as well.

### CODE REVIEW

**Comment by prometheanfire** [comment]
???

**Comment by prometheanfire** [comment]
Well, I'm including this in my package, this is taking too long

**Comment by prometheanfire** [comment]
@dnsmichi

**Comment by Al2Klimov** [comment]
Obsolete as the changed files have gone.

**Pull request closed without merging**
