### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by nilmerg**
The screenshots in the README.md and About-Chapter are still subject to change.

Documentation is complete. Please review.

refs #67

### CODE REVIEW

**Comment by Al2Klimov** [comment]
As discussed w/ @nilmerg (offline):

The violation of the requirement I'm missing in the doc is a theoretical edge case which maybe didn't ever occurr (yet) as we didn't release a v1.0, yet. Most people don't even have more than one Icinga 2 cluster. So we don't have to mention this.

What's your opinion on this, @bobapple?

**Comment by bobapple** [comment]
Currently we're not listing the monitoring module as requirement in any other Icinga Web 2 module. I wouldn't list it here as well.

**Comment by nilmerg** [comment]
@bobapple Should be final now.

**Comment by Al2Klimov** [comment]
@nilmerg No it isn't. Please unsquash your changes as they are from more than one author.

**Comment by nilmerg** [comment]
done

**Comment by Thomas-Gelf** [comment]
Hi @bobapple!

> Currently we're not listing the monitoring module as requirement in any other Icinga Web 2 module. I wouldn't list it here as well.

Some generic thoughts related to above comment:

* DO NOT depend on modules whose hooks you're going to implement, because that's not a hard dependency. I can for example provide an ImportSource for the Icinga Director without having Director installed. That will not do any harm.
* DO depend on modules whose library code you're going to use. e.g. a module depending on the monitoring module's Data abstraction layer to figure out whether you're allowed to show a specific host has a hard dependency on that module. It would fail once someone is running without that module.

A mixed mode module could be one allowing a "full" access only with it's very own dedicated permission, and restricted access with special controller actions usually accessed through links provided by dedicated hooks. Such a module still has a soft dependency, but no need to put it into module.info. If your module offers URLs that once clicked would result in an Exception because of missing library code, it should definitively have a dependency in place. Even if we do not (yet) enforce them.

Cheers,
Thomas

**Comment by Al2Klimov** [comment]
@Thomas-Gelf Even if we didn't need the monitoring mod to restrict access (which is the only reasonable solution), we still need it to know that mon. objects there are.

**Comment by Thomas-Gelf** [comment]
@Al2Klimov: then it is a hard requirement.

**Pull request merged**
