### PR TITLE
Make all macros used in a template's metrics filters available in its functions, too

### LINKED ISSUE #187: It is not possible to combine two distinct metrics in the same chart: support to allow $service_name_template$ at least
Hi, 

currently there is not possible to make a combined chart of two distinct metrics in the same service:

```ini
[sys-event_io_waits.metrics_filters]
waits = "$service_name_template$.perfdata.waits.value"
time = "$service_name_template$.perfdata.time.value"
```

What I need is the following quotient:

```ini
[sys-event_io_waits.functions]
time_per_wait = "
divideSeries(
    perSecond($service_name_template$.perfdata.waits.value),
    perSecond($service_name_template$.perfdata.time.value)
)
"
```

But icinga complains: 

```
Metrics filter for curve "time_per_wait" of template "sys-event_io_waits" in file "/usr/local/www/icingaweb2/modules/graphite/templates/icinga2/sys-event_io_wait.ini" missing

Please add support to allow plotting metrics derived from others.

Thanks!

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #187

### CODE REVIEW

**Comment by Al2Klimov** [comment]
_bump_

**Review by bobapple — APPROVED** [review]

**Comment by Virsacer** [comment]
Now my CPU template does not output a graph anymore

```
[cpu.metrics_filters]
load1 = "$service_name_template$.perfdata.load1.value"
load5 = "$service_name_template$.perfdata.load5.value"
load15 = "$service_name_template$.perfdata.load15.value"
total1 = "$service_name_template$.perfdata.total_1m.value"
total5 = "$service_name_template$.perfdata.total_5m.value"
total15 = "$service_name_template$.perfdata.total_15m.value"
[cpu.functions]
load1 = "alias(color($metric$,'#44BB77'),'Load 1')"
load5 = "alias(color($metric$,'#FFAA44'),'Load 5')"
load15 = "alias(color($metric$,'#FF5566'),'Load 15')"
total1 = "alias(color($metric$,'#44BB77'),'Load 1')"
total5 = "alias(color($metric$,'#FFAA44'),'Load 5')"
total15 = "alias(color($metric$,'#FF5566'),'Load 15')"
```
Some checks have the load* perfdata and some have the total_*m perfdata but none has both...

**Comment by Virsacer** [comment]
This fixes it:
```
--- a/library/Graphite/Web/Widget/GraphImage.php
+++ b/library/Graphite/Web/Widget/GraphImage.php
@@ -94,7 +94,7 @@ class GraphImage extends AbstractWidget
             $allVars = [];
 
             foreach ($template->getCurves() as $curveName => $curve) {
-                $vars = $curve[0]->reverseResolve($metrics[$curveName]);
+                $vars = $curve[0]->reverseResolve(@$metrics[$curveName]);
 
                 if ($vars !== false) {
                     $allVars = array_merge($allVars, $vars);
```

**Comment by Al2Klimov** [comment]
Please open a PR and use _if isset_, not _at_.

**Pull request merged**
