### PR TITLE
fix for  graph height declared in template

### LINKED ISSUE #234: Graph is not resized properly (height is capped)
## Expected Behavior

Read height and width from the template and apply it correctly. 

## Current Behavior

If height and width are passed directly in the url then the graph has the correct size.
But if the arguments are passed as 'urlparams' in the template file, then the height is capped and not applied correctly.

## Possible Solution

Graphite itself renders the image correctly; the problem seems to lie in the container surrounding the image.

## Steps to Reproduce (for bugs)

Template file with height and width: 
````
[check-eps.graph]
check_command = "check-eps"

[check-eps.metrics_filters]
hoher="$host_name_template$.perfdata.Alarme_mit_hoher_Einstufung.value"
mittler="$host_name_template$.perfdata.Alarme_mit_mittlerer_Einstufung.value"
info="$host_name_template$.perfdata.Informationshinweise.value"
good="$host_name_template$.perfdata.Ohne_Alarme.value"

[check-eps.urlparams]
graphType=pie
valueLabels=number
valueLabelsMin=1
colorList=red,orange,yellow,green
hideLegend=true
height=600
width=600
````
This produces following output in Icinga:
params_in_template

If the same template is used but without height and width specified, the output is as follows:
without_params

Height and width can then be passed directly in the browser via the url:
params_in_url

## Context

The graph is simply too small for our purpose.

## Your Environment

* Module version (System - About): 2.7.3
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (icinga2 --version):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.4-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 18.04.2 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 4.15.0-65-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 7.3.0
  Build host: b2ecadfb68ab

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* Graphite (carbon, web, whisper) version: 1.1.0
* Operating System and version: Ubuntu Server 18.04
* Webserver, PHP versions: Apache 2 + PHP 7.2

### PR DESCRIPTION
**Pull request by dheule**
This shuld fix #234

### CODE REVIEW

**Comment by nilmerg** [comment]
@cla-bot check

**Comment by bobapple** [comment]
@cla-bot check

**Comment by nilmerg** [comment]
Doesn't work for me.
Screenshot from 2022-03-22 12-04-24

There seems to be something wrong with how the template params `height` and `width` are handled anyway. If you want to continue, please let me know, I will then describe the solution I think we need in the issue.

**Comment by dheule** [comment]
> Doesn't work for me. Screenshot from 2022-03-22 12-04-24
> 
> There seems to be something wrong with how the template params `height` and `width` are handled anyway. If you want to continue, please let me know, I will then describe the solution I think we need in the issue.

Hi @nilmerg ,

I have only added the parameter processing from the height graph template to the render view, this is working.

But for Pie graphs, you also need a fixed width. I will look at this at the next few weeks, atm i have no time to implemnt this asap.

So please stay tuned for the next update. This pull request only helps for normal graphs with needs a bigger height.

Best regards,
Daniel

**Review by nilmerg — APPROVED** [review]
Yeah, looks correct now. No matter if I define only a width, or height, or both. :+1:

**Pull request merged**
